###############################################################################
#
# (c) Copyright IBM Corp. 2016
#
#  This program and the accompanying materials are made available
#  under the terms of the Eclipse Public License v1.0 and
#  Apache License v2.0 which accompanies this distribution.
#
#      The Eclipse Public License is available at
#      http://www.eclipse.org/legal/epl-v10.html
#
#      The Apache License v2.0 is available at
#      http://www.opensource.org/licenses/apache2.0.php
#
# Contributors:
#    Multiple authors (IBM Corp.) - initial implementation and documentation
###############################################################################

language: c++
sudo: false

# https://docs.travis-ci.com/user/caching/
#cache: ccache
dist: trusty
addons:
  artifacts:
    debug: true
    paths:
      build/CMakeCache.txt
      build/CTestTestfile.cmake
  apt:
    packages:
       - libnuma-dev
       - bison
       - gcc-multilib
       - g++-multilib
       - g++-arm-linux-gnueabi
       - clang-3.4
       - libclang-3.4-dev
       - llvm-3.4
       #TODO should only be on arm compiles
       - qemu-user-static
matrix:
  include:
  - os: linux
  - os: osx
  - os: linux
    env: ARCH=arm
    script:
      - mkdir native_build
      - cd native_build
      - cmake -Wdev ..
      - cmake --build . --target tracegen
      - cmake --build . --target hookgen
      - cd ..
      - mkdir -p build
      - cd build
      - export QEMU_LD_PREFIX=/usr/arm-linux-gnueabi
      - cmake -Wdev -DCMAKE_TOOLCHAIN_FILE=../scripts/arm.toolchain -DCROSSCOMPILING_EMULATOR=qemu-arm-static -DOMR_TOOLS_IMPORT_FILE=native_build/tools/ImportTools.cmake ..
      - cmake --build .
      - ctest -V

before_script:
  - ulimit -c unlimited
  - export GTEST_COLOR=1
  - export GTEST_FILTER=-*dump_test_create_dump_*:*NumaSetAffinity:*NumaSetAffinitySuspended
  # Disable the core dump tests as container based builds don't allow setting
  # core_pattern and don't have apport installed.  This can be removed when
  # apport is available in apt whitelist
  # blah

script:
  - mkdir -p build
  - cd build
  - cmake -Wdev ..
  - cmake --build .
  - ctest -V
