###############################################################################
#
# (c) Copyright IBM Corp. 2016
#
#  This program and the accompanying materials are made available
#  under the terms of the Eclipse Public License v1.0 and
#  Apache License v2.0 which accompanies this distribution.
#
#      The Eclipse Public License is available at
#      http://www.eclipse.org/legal/epl-v10.html
#
#      The Apache License v2.0 is available at
#      http://www.opensource.org/licenses/apache2.0.php
#
# Contributors:
#    Multiple authors (IBM Corp.) - initial implementation and documentation
###############################################################################

language: c++
sudo: false

# https://docs.travis-ci.com/user/caching/
cache: ccache

addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - cmake
       - libnuma-dev
       - bison
       - gcc-multilib
       - g++-multilib
       - clang-3.4
       - libclang-3.4-dev
       - llvm-3.4
       - wget

before_script:
  - ulimit -c unlimited
  - export GTEST_FILTER=-*dump_test_create_dump_*:*NumaSetAffinity:*NumaSetAffinitySuspended
  # Disable the core dump tests as container based builds don't allow setting
  # core_pattern and don't have apport installed.  This can be removed when
  # apport is available in apt whitelist
  - wget http://www.cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.tar.gz
  - tar -xf cmake-3.6.3-Linux-x86_64.tar.gz
  - export PATH=$PWD/cmake-3.6.3-Linux-x86_64/bin:$PATH


script:
  - mkdir -p build
  - cd build
  - cmake -Wdev ..
  - cmake --build .
  - cmake --build . --target test
