###############################################################################
#
# (c) Copyright IBM Corp. 2016
#
#  This program and the accompanying materials are made available
#  under the terms of the Eclipse Public License v1.0 and
#  Apache License v2.0 which accompanies this distribution.
#
#      The Eclipse Public License is available at
#      http://www.eclipse.org/legal/epl-v10.html
#
#      The Apache License v2.0 is available at
#      http://www.opensource.org/licenses/apache2.0.php
#
# Contributors:
#    Multiple authors (IBM Corp.) - initial implementation and documentation
###############################################################################

language: c++
sudo: false

# https://docs.travis-ci.com/user/caching/
cache: ccache
dist: trusty
addons:
  artifacts:
    debug: true
    paths:
      build/CMakeCache.txt
  apt:
    packages:
       - libnuma-dev
       - bison
       - gcc-multilib
       - g++-multilib
       - g++-arm-linux-gnueabi
       - clang-3.4
       - libclang-3.4-dev
       - llvm-3.4
matrix:
  include:
  - os: linux
  - os: osx
  - os: linux
    env: TOOLCHAIN="-DCMAKE_TOOLCHAIN_FILE=../scripts/arm.toolchain"  TOOLS_IMPORT="-DOMR_TOOLS_IMPORT_FILE=../native_build/tools/ImportTools.cmake"
    before_script:
      - mkdir native_build
      - cd native_build
      - cmake -Wdev ..
      - cmake --build . --target tracegen
      - cmake --build . --target hookgen
      - cd ..

before_script:
  - ulimit -c unlimited
  - export GTEST_COLOR=1
  - export GTEST_FILTER=-*dump_test_create_dump_*:*NumaSetAffinity:*NumaSetAffinitySuspended
  # Disable the core dump tests as container based builds don't allow setting
  # core_pattern and don't have apport installed.  This can be removed when
  # apport is available in apt whitelist

script:
  - mkdir -p build
  - cd build
  - cmake -Wdev $TOOLCHAIN $TOOLS_IMPORT ..
  - cmake --build .
  - ctest -V
