# C/C++ with GCC
resources:
  containers:
  - container: dev
    image: devin122/build_test

pool:
  vmImage: 'Ubuntu 16.04'
container: dev

steps:
- script: |
    mkdir build
    cd build
    cmake -C ../cmake/caches/Travis.cmake ..
    make
  displayName: 'make'
