# C/C++ with GCC

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo apt-get install libnuma-dev bison libdwarf-dev libelf-dev
    mkdir build
    cd build
    cmake -C ../cmake/caches/Travis.cmake ..
    make
  displayName: 'make'
